Suppression d'une section de single.html
hugo génère une erreur à cause de cette section :

    Error: error building site: render: failed to render pages: render of "/Users/cassou/personal/projects/cantine/AnDaolVras.github.io/content/blog/Bonjour.md" failed: "/Users/cassou/personal/projects/cantine/AnDaolVras.github.io/themes/blank/layouts/_default/single.html:18:16": execute of template failed: template: _default/single.html:18:16: executing "main" at <.Site.DisqusShortname>: can't evaluate field DisqusShortname in type page.Site